FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y gcc python3-devel && yum clean all

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["main.handler"]
